AWSTemplateFormatVersion: '2010-09-09'
Description: "Driver Template to deploy lambda functions"

Parameters:
  project:
    Type: String
    Default: ippei
    Description: Project Name
  env:
    Type: String
    Default: stage
    AllowedValues: [prod, dev, qa, stage]
    Description:  Environment Name
  app:
    Type: String
    Default: app
    Description: Name of the app
  s3ArtifactPath:
    Type: String
    Default: "https://ippei-wordpress-prod-us-east-1-770760105158.s3.amazonaws.com/code/cfn/services"
    Description: "Artifact Bucket path"

Resources:
  customAlarmsLambdaFunc:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${s3ArtifactPath}/lambdaFunction/lambdaFunction-app.yml"
      Parameters:
        project: !Ref project
        env: !Ref env
        lambdaFunctionName: !Sub "${project}-${env}-${app}-updateCustomAlarms-${AWS::Region}"
        runtimeVersion: python3.10
        lambdaHandler: updateCustomCloudWatchAlarms.lambda_handler
        timeout: 30
        lambdaExecutionRoleArn: !GetAtt iamRoles.Outputs.lambdaRoleForCustomAlarms
        s3BucketName: cloudweb-wordpress-artifacts-us-east-1-770760105158
        s3Key: updateCustomCloudWatchAlarms.zip
        launchTemplateName: !Sub "${project}-${env}-${app}-LaunchTemplateforASG"
        instanceIdsParamStore: !Sub "${project}-${env}-${app}-instanceIdParamStore-${AWS::Region}"
        memMetricName: mem_used_percent
        diskMetricName: disk_used_percent
        asgName: !Sub "${project}-${env}-${app}-AutoScalingGroup"
  
  createAmiLambdaFunc:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${s3ArtifactPath}/lambdaFunction/lambdaFunction-app.yml"
      Parameters:
        project: !Ref project
        env: !Ref env
        lambdaFunctionName: !Sub "${project}-${env}-${app}-createAmi-${AWS::Region}"
        runtimeVersion: python3.10
        lambdaHandler: createAmi.lambda_handler
        timeout: 30
        lambdaExecutionRoleArn: !GetAtt iamRoles.Outputs.lambdaRoleForCreateAmiFunctionArn
        s3BucketName: cloudweb-wordpress-artifacts-us-east-1-770760105158
        s3Key: createAmi.zip
        launchTemplateName: !Sub "${project}-${env}-${app}-LaunchTemplateforASG"
        instanceIdsParamStore: !Sub "${project}-${env}-${app}-instanceIdParamStore-${AWS::Region}"
        memMetricName: mem_used_percent
        diskMetricName: disk_used_percent
        asgName: !Sub "${project}-${env}-${app}-AutoScalingGroup"

  updateAsgLaunchTemplateLambdaFunc:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${s3ArtifactPath}/lambdaFunction/lambdaFunction-app.yml"
      Parameters:
        project: !Ref project
        env: !Ref env
        lambdaFunctionName: !Sub "${project}-${env}-${app}-updateAsgLaunchTemplate-${AWS::Region}"
        runtimeVersion: python3.10
        lambdaHandler: updateAsgLaunchTemplate.lambda_handler
        timeout: 30
        lambdaExecutionRoleArn: !GetAtt iamRoles.Outputs.lambdaRoleForAsgLaunchTemplateArn
        s3BucketName: cloudweb-wordpress-artifacts-us-east-1-770760105158
        s3Key: updateAsgLaunchTemplate.zip
        launchTemplateName: !Sub "${project}-${env}-${app}-LaunchTemplateforASG"
        instanceIdsParamStore: !Sub "${project}-${env}-${app}-instanceIdParamStore-${AWS::Region}"
        memMetricName: mem_used_percent
        diskMetricName: disk_used_percent
        asgName: !Sub "${project}-${env}-${app}-AutoScalingGroup"

Outputs:
  customAlarmsLambdaFuncId:
    Value: !Ref customAlarmsLambdaFunc
    Export:
      Name: !Sub '${project}-${env}-${app}-customAlarmsLambdaFuncId-${AWS::Region}' 
  customAlarmsLambdaFuncArn:
    Value: !GetAtt customAlarmsLambdaFunc.Arn
    Export:
      Name: !Sub '${project}-${env}-${app}-customAlarmsLambdaFuncArn-${AWS::Region}' 
  createAmiLambdaFuncId:
    Value: !Ref createAmiLambdaFunc
    Export:
      Name: !Sub '${project}-${env}-${app}-createAmiLambdaFuncId-${AWS::Region}' 
  createAmiLambdaFuncArn:
    Value: !GetAtt createAmiLambdaFunc.Arn
    Export:
      Name: !Sub '${project}-${env}-${app}-createAmiLambdaFuncArn-${AWS::Region}' 
  updateAsgLaunchTemplateLambdaFuncId:
    Value: !Ref updateAsgLaunchTemplateLambdaFunc
    Export:
      Name: !Sub '${project}-${env}-${app}-updateAsgLaunchTemplateLambdaFuncId-${AWS::Region}'
  updateAsgLaunchTemplateLambdaFuncArn:
    Value: !GetAtt updateAsgLaunchTemplateLambdaFunc.Arn
    Export:
      Name: !Sub '${project}-${env}-${app}-updateAsgLaunchTemplateLambdaFuncArn-${AWS::Region}' 