AWSTemplateFormatVersion: 2010-09-09 
Description: Driver template to deploy the VPC security groups
Parameters:
  project:
    Type: String
    Default: cloudweb
    Description:  Project Name 
  env:
    Type: String
    Default: prod
    AllowedValues: [prod, dev, qa]
    Description:  Environment Name

  s3ArtifactPath:
    Type: String
    Default: "https://cloudweb-wordpress-prod-us-east-1-770760105158.s3.amazonaws.com/code/cfn/services"
    Description: "Artifact bucket path"
Resources:
  securityGroup:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - vpc
    Properties:
      TemplateURL: !Sub "${s3ArtifactPath}/securitygroup/securitygroup-app.yml"
      Parameters:
        project: !Ref project
        env: !Ref env
        app: !Ref app
        vpcId: !GetAtt vpc.Outputs.vpcId
        sgInternetTrafficIngressCidr: 0.0.0.0/0
        sgInternetTrafficEgressCidr: 0.0.0.0/0
        sgSshPort: 22
        sgHttpsPort: 443
        sgHttpPort: 80
        sgRdsPort: 3306
        sgAllowAllEgressProtocol: -1
        netsolCidrIp: 0.0.0.0/0
Outputs:
  securityGroup:
    Value: !Ref securityGroup
    Export:
      Name: !Sub "${project}-${env}-${app}-securitygroup-${AWS::Region}"
  

