AWSTemplateFormatVersion: 2010-09-09
Description: Driver template to deploy the cloudfront 
Parameters:
  project:
    Type: String
    Default: cloudweb
    Description:  Project Name
  env:
    Type: String
    Default: stag
    AllowedValues: [prod, dev, qa, stag]
    Description:  Environment Name
  s3ArtifactPath:
    Type: String
    Default: "https://cloudweb-wordpress-prod-us-east-1-770760105158.s3.amazonaws.com/code/cfn/services"
    Description: "Artifact bucket path"
  
Resources: 
  cloudFrontDistribution:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - cloudWebApplicationLoadBalancer
      - s3CfAccessLogBucket
    Properties:
      TemplateURL: !Sub "${s3ArtifactPath}/cloudfront/cloudfront-app.yml"
      Parameters:
        project: !Ref project
        env: !Ref env
       cfDistributionStatus: true
        defaultTTL:  86400
        maxTTL: 259300
        minTTL:  86400
        targetDns: !GetAtt cloudWebApplicationLoadBalancer.Outputs.lbDnsName
        targetOriginId: !Sub "${env}LoadBalancerOrigin"
        viewerProtocolPolicy: redirect-to-https
        originProtocolPolicy: https-only
        acmCertificateIdentifier: ebcca23e-3406-488a-be5d-ac0050acfbc6
        cfHttpsPort: 443
        cfOriginSSLProtocols: TLSv1.2
        cfAlias: netsolcloudservices.com
        cfOriginRequestPolicyId: 216adef6-5c7f-47e4-b989-5492eafa07d3
        cfResponseHeadersPolicyId: 67f7725c-6f97-4210-82d7-5512b31e9d03
        cfHttpVersion: http2
        cfPriceClass: PriceClass_100
        acmCertificateProtocolVersion: TLSv1.2_2021
        acmCertificateSslSupportMethod: sni-only
        cfCachePolicyConfigComment: TTL for cache in cloudfront with ALB as an origin
        cfCachePolicyConfigName: !Sub "${project}-${env}-cfCachePolicyWithAlbOrigin"
        cfCachePolicyCookieBehavior: all
        cfCachePolicyHeaderBehavior: whitelist
        s3CfAccessLogBucketDomainName: !GetAtt s3CfAccessLogBucket.Outputs.s3BucketDomainName
        accessLogCookies: true
        accessLogPrefix: cloudFrontAccessLogs/
        cfDistComment: !Sub ${env} cloudfront distribution
        cfOriginAccessIdentityComment: ""
        s3BucketDomainName: ""
        s3OriginId: ""
        s3PathPattern: /maintenance/*
        isEnableCfLogging: yes
        cfCacheDisablePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad
        cfEnableCacheRequestPolicy: no
        cfDistExportName: cfDist1
        enableAlias: yes

Outputs:
  cloudFrontDistribution:
    Value: !Ref cloudFrontDistribution
    Export:
      Name: !Sub "${project}-${env}-cloudFrontDistribution-${AWS::Region}"