AWSTemplateFormatVersion: '2010-09-09'
Description: Driver template to create S3 buckets
Parameters:
  project:
    Type: String
    Default: ippei
    Description:  Project Name
  env:
    Type: String
    Default: stage
    AllowedValues: [prod, dev, qa, stage]
    Description:  Environment Name
  app:
    Type: String
    Default: app
    Description: Name of the app  
  s3ArtifactPath:
    Type: String
    Default: "https://ippei-wordpress-prod-us-east-1-770760105158.s3.amazonaws.com/code/cfn/services"
    Description: "Artifact bucket path"

Resources:  
  s3AlbAccessLogBucket:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${s3ArtifactPath}/s3/s3-app.yml"
      Parameters:
        project: !Ref project
        env: !Ref env
        app: alb-logs
        s3BucketAccessControl: Private
        s3VersioningStatus: Enabled
        s3ObjectOwnership: BucketOwnerPreferred
        sseAlgorithm: AES256
        indexDocument: index.html
        errorDocument: error.html
        enableWebsiteConfiguration: no
        enableCfWritePolicy: no
        enableS3BucketPolicy: no 
        enableAlbBucketPolicy: yes
  
  s3CfAccessLogBucket:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${s3ArtifactPath}/s3/s3-app.yml"
      Parameters:
        project: !Ref project
        env: !Ref env
        s3BucketAccessControl: Private
        s3VersioningStatus: Enabled
        linkedinUrl: https://www.linkedin.com
        # keapUrl: https://keap.app
        s3ObjectOwnership: BucketOwnerPreferred
        sseAlgorithm: AES256

Outputs:
  s3ArtifactsBucket:
    Value: !Ref s3ArtifactsBucket
    Export:
      Name: !Sub "${project}-${env}-s3ArtifactsBucket-${AWS::Region}"
  s3CfAccessLogBucket:
    Value: !Ref s3CfAccessLogBucket
    Export:
      Name: !Sub "${project}-${env}-s3CfAccessLogBucketStack-${AWS::Region}"